name: Deploy Charge Finder BFF

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "charge-finder-bff/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build Binary
        working-directory: charge-finder-bff  # Navigate to the correct directory
        run: |
          go build -o charge-finder-api

      - name: Setup SSH and Deploy  # Fix: Now this is a separate step!
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: "charge-finder-api"
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh

          # Add private key to SSH
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Add server to known hosts (to prevent manual prompt)
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

          # Deploy files using SCP
          scp -i ~/.ssh/id_ed25519 charge-finder-bff/charge-finder-api $SSH_USER@$SSH_HOST:/var/www/charge-finder-api/

          # Set correct permissions and restart service
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST << 'EOF'
            sudo chmod +x /var/www/charge-finder-api/charge-finder-api
            sudo systemctl restart charge-finder-api
            sudo systemctl status charge-finder-api --no-pager --lines=10
          EOF